// <auto-generated />
using System;
using Inventory.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventory.Infrastructure.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260902183754_AddReservationReleasedAt")]
    partial class AddReservationReleasedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inventory.Infrastructure.Entities.ProcessedMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("MessageId", "ConsumerName");

                    b.ToTable("ProcessedMessages", (string)null);
                });

            modelBuilder.Entity("Inventory.Infrastructure.Entities.StockItem", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("int");

                    b.Property<int>("QuantityReserved")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("StockItems", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            QuantityOnHand = 42,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 2,
                            QuantityOnHand = 65,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 3,
                            QuantityOnHand = 18,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 4,
                            QuantityOnHand = 73,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 5,
                            QuantityOnHand = 31,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 6,
                            QuantityOnHand = 57,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 7,
                            QuantityOnHand = 24,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 8,
                            QuantityOnHand = 88,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 9,
                            QuantityOnHand = 12,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 10,
                            QuantityOnHand = 46,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 11,
                            QuantityOnHand = 120,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 12,
                            QuantityOnHand = 95,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 13,
                            QuantityOnHand = 140,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 14,
                            QuantityOnHand = 78,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 15,
                            QuantityOnHand = 163,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 16,
                            QuantityOnHand = 54,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 17,
                            QuantityOnHand = 132,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 18,
                            QuantityOnHand = 87,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 19,
                            QuantityOnHand = 109,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 20,
                            QuantityOnHand = 71,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 21,
                            QuantityOnHand = 35,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 22,
                            QuantityOnHand = 22,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 23,
                            QuantityOnHand = 48,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 24,
                            QuantityOnHand = 16,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 25,
                            QuantityOnHand = 61,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 26,
                            QuantityOnHand = 29,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 27,
                            QuantityOnHand = 43,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 28,
                            QuantityOnHand = 19,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 29,
                            QuantityOnHand = 55,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 30,
                            QuantityOnHand = 27,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 31,
                            QuantityOnHand = 210,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 32,
                            QuantityOnHand = 175,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 33,
                            QuantityOnHand = 240,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 34,
                            QuantityOnHand = 158,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 35,
                            QuantityOnHand = 192,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 36,
                            QuantityOnHand = 226,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 37,
                            QuantityOnHand = 143,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 38,
                            QuantityOnHand = 268,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 39,
                            QuantityOnHand = 181,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 40,
                            QuantityOnHand = 205,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 41,
                            QuantityOnHand = 68,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 42,
                            QuantityOnHand = 52,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 43,
                            QuantityOnHand = 91,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 44,
                            QuantityOnHand = 37,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 45,
                            QuantityOnHand = 76,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 46,
                            QuantityOnHand = 44,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 47,
                            QuantityOnHand = 83,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 48,
                            QuantityOnHand = 59,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 49,
                            QuantityOnHand = 102,
                            QuantityReserved = 0
                        },
                        new
                        {
                            ProductId = 50,
                            QuantityOnHand = 33,
                            QuantityReserved = 0
                        });
                });

            modelBuilder.Entity("Inventory.Infrastructure.Entities.StockReservation", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("OrderId");

                    b.ToTable("StockReservations", (string)null);
                });

            modelBuilder.Entity("Inventory.Infrastructure.Entities.StockReservation", b =>
                {
                    b.OwnsMany("Inventory.Infrastructure.Entities.StockReservationLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("ProductId")
                                .HasColumnType("int");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int");

                            b1.HasKey("OrderId", "Id");

                            b1.ToTable("StockReservationLines", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
