// <auto-generated />
using System;
using Catalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Infrastructure.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tazas"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Llaveros"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Playeras"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Pines"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Libretas"
                        });
                });

            modelBuilder.Entity("Catalog.Infrastructure.Entities.ProcessedMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("MessageId", "ConsumerName");

                    b.ToTable("ProcessedMessages", (string)null);
                });

            modelBuilder.Entity("Catalog.Infrastructure.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("PreviousPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("PriceChangedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Taza de cerámica pintada a mano con el patrón azul cobalto de la talavera poblana. Capacidad de 350 ml, apta para microondas.",
                            ImageUrl = "/img/products/taza-001.jpg",
                            Name = "Taza Talavera Puebla",
                            Price = 249.00m,
                            Sku = "TAZA-001",
                            Stock = 42
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Taza esmaltada en negro con una Catrina serigrafiada en dorado. El diseño se revela por completo al llenarla con líquido caliente.",
                            ImageUrl = "/img/products/taza-002.jpg",
                            Name = "Taza Calavera Catrina",
                            Price = 229.00m,
                            Sku = "TAZA-002",
                            Stock = 65
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Taza de 400 ml decorada con los colores y grecas de los alebrijes de San Martín Tilcajete. Cada pieza tiene variaciones de pintura.",
                            ImageUrl = "/img/products/taza-003.jpg",
                            Name = "Taza Alebrije Oaxaqueño",
                            Price = 269.00m,
                            Sku = "TAZA-003",
                            Stock = 28
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Taza de cerámica mate con la Piedra del Sol grabada en relieve. Asa reforzada y base antideslizante.",
                            ImageUrl = "/img/products/taza-004.jpg",
                            Name = "Taza Sol Azteca",
                            Price = 199.00m,
                            Sku = "TAZA-004",
                            Stock = 73
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Taza artesanal de barro negro de San Bartolo Coyotepec, bruñida a mano. Pieza única; no apta para microondas.",
                            ImageUrl = "/img/products/taza-005.jpg",
                            Name = "Taza Barro Negro",
                            Price = 289.00m,
                            Sku = "TAZA-005",
                            Stock = 19
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Taza de 350 ml con las cartas clásicas de la lotería impresas alrededor: el gallo, la sirena, el catrín y el nopal.",
                            ImageUrl = "/img/products/taza-006.jpg",
                            Name = "Taza Lotería Mexicana",
                            Price = 179.00m,
                            Sku = "TAZA-006",
                            Stock = 88
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Taza con relieve de nopal esmaltado en verde y borde color arena. Diseño minimalista para uso diario.",
                            ImageUrl = "/img/products/taza-007.jpg",
                            Name = "Taza Cactus Esmaltada",
                            Price = 189.00m,
                            Sku = "TAZA-007",
                            Stock = 54
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Taza de cerámica blanca con retrato ilustrado y corona de flores a todo color. Impresión resistente al lavavajillas.",
                            ImageUrl = "/img/products/taza-008.jpg",
                            Name = "Taza Frida Retrato",
                            Price = 259.00m,
                            Sku = "TAZA-008",
                            Stock = 37
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "Taza de 90 ml para espresso, decorada a mano con motivos de talavera. Se vende individualmente.",
                            ImageUrl = "/img/products/taza-009.jpg",
                            Name = "Taza Talavera Mini Espresso",
                            Price = 149.00m,
                            Sku = "TAZA-009",
                            Stock = 96
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "Taza de 400 ml con la silueta de la Pirámide del Sol grabada en láser sobre esmalte terracota.",
                            ImageUrl = "/img/products/taza-010.jpg",
                            Name = "Taza Pirámide de Teotihuacán",
                            Price = 239.00m,
                            Sku = "TAZA-010",
                            Stock = 31
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Description = "Llavero de calavera en plata .925 con detalles cincelados a mano. Argolla reforzada de acero inoxidable.",
                            ImageUrl = "/img/products/llav-001.jpg",
                            Name = "Llavero Calavera de Plata",
                            Price = 89.00m,
                            Sku = "LLAV-001",
                            Stock = 120
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "Alebrije en miniatura tallado en madera de copal y pintado a mano. Cada pieza tiene una combinación de colores distinta.",
                            ImageUrl = "/img/products/llav-002.jpg",
                            Name = "Llavero Alebrije Tallado",
                            Price = 79.00m,
                            Sku = "LLAV-002",
                            Stock = 84
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Description = "Sombrero charro en miniatura de fieltro con bordado dorado en el ala. Incluye argolla y mosquetón.",
                            ImageUrl = "/img/products/llav-003.jpg",
                            Name = "Llavero Sombrero Charro",
                            Price = 55.00m,
                            Sku = "LLAV-003",
                            Stock = 110
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Description = "Réplica del calendario azteca en zamak con acabado bronce envejecido. Diámetro de 4 cm.",
                            ImageUrl = "/img/products/llav-004.jpg",
                            Name = "Llavero Piedra del Sol",
                            Price = 69.00m,
                            Sku = "LLAV-004",
                            Stock = 92
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Description = "Llavero de fieltro con nopal bordado a mano en hilo verde y flor rosa. Ligero y flexible.",
                            ImageUrl = "/img/products/llav-005.jpg",
                            Name = "Llavero Cactus Bordado",
                            Price = 49.00m,
                            Sku = "LLAV-005",
                            Stock = 105
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Description = "Máscara de luchador en miniatura, cosida en tela elástica con detalles metálicos. Cuatro diseños clásicos surtidos.",
                            ImageUrl = "/img/products/llav-006.jpg",
                            Name = "Llavero Máscara de Lucha Libre",
                            Price = 75.00m,
                            Sku = "LLAV-006",
                            Stock = 67
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Description = "Chile habanero de resina con acabado brillante y hoja en verde esmaltado. Medida aproximada de 5 cm.",
                            ImageUrl = "/img/products/llav-007.jpg",
                            Name = "Llavero Chile Habanero",
                            Price = 45.00m,
                            Sku = "LLAV-007",
                            Stock = 118
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Description = "Colibrí en metal esmaltado a fuego con degradado turquesa y verde. Pieza de dos caras.",
                            ImageUrl = "/img/products/llav-008.jpg",
                            Name = "Llavero Colibrí Esmaltado",
                            Price = 95.00m,
                            Sku = "LLAV-008",
                            Stock = 41
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Description = "Medallón de cerámica de talavera pintado a mano, montado sobre argolla de acero. Motivo floral azul.",
                            ImageUrl = "/img/products/llav-009.jpg",
                            Name = "Llavero Talavera Redondo",
                            Price = 59.00m,
                            Sku = "LLAV-009",
                            Stock = 76
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Description = "Ajolote rosa de resina translúcida con branquias en relieve. El favorito del catálogo entre los visitantes de Xochimilco.",
                            ImageUrl = "/img/products/llav-010.jpg",
                            Name = "Llavero Ajolote de Resina",
                            Price = 85.00m,
                            Sku = "LLAV-010",
                            Stock = 58
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            Description = "Playera de algodón peinado con ilustración de ajolote serigrafiada al frente. Corte unisex, tallas S a XL.",
                            ImageUrl = "/img/products/play-001.jpg",
                            Name = "Playera Ajolote Xochimilco",
                            Price = 329.00m,
                            Sku = "PLAY-001",
                            Stock = 45
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            Description = "Playera negra con máscara de luchador estampada en cuatro tintas. Algodón 180 g, cuello reforzado.",
                            ImageUrl = "/img/products/play-002.jpg",
                            Name = "Playera Lucha Libre",
                            Price = 349.00m,
                            Sku = "PLAY-002",
                            Stock = 62
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            Description = "Playera blanca con Catrina serigrafiada a mano en tinta negra y detalles en dorado. Edición limitada.",
                            ImageUrl = "/img/products/play-003.jpg",
                            Name = "Playera Catrina Serigrafía",
                            Price = 299.00m,
                            Sku = "PLAY-003",
                            Stock = 71
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            Description = "Playera color arena con el águila del escudo nacional estampada en el pecho. Algodón orgánico.",
                            ImageUrl = "/img/products/play-004.jpg",
                            Name = "Playera Águila Real",
                            Price = 279.00m,
                            Sku = "PLAY-004",
                            Stock = 53
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            Description = "Playera con bordado otomí hecho a mano en el cuello y el puño, con figuras de animales en hilo multicolor.",
                            ImageUrl = "/img/products/play-005.jpg",
                            Name = "Playera Otomí Bordada",
                            Price = 399.00m,
                            Sku = "PLAY-005",
                            Stock = 22
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            Description = "Playera azul marino con el mapa de México ilustrado por regiones y sus platillos típicos.",
                            ImageUrl = "/img/products/play-006.jpg",
                            Name = "Playera Mapa de México",
                            Price = 259.00m,
                            Sku = "PLAY-006",
                            Stock = 89
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            Description = "Playera blanca con un nopal en línea fina bordado en el bolsillo. Diseño discreto de uso diario.",
                            ImageUrl = "/img/products/play-007.jpg",
                            Name = "Playera Cactus Minimalista",
                            Price = 249.00m,
                            Sku = "PLAY-007",
                            Stock = 94
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            Description = "Playera negra con ofrenda de Día de Muertos estampada a todo color, con tintas que brillan en la oscuridad.",
                            ImageUrl = "/img/products/play-008.jpg",
                            Name = "Playera Día de Muertos",
                            Price = 359.00m,
                            Sku = "PLAY-008",
                            Stock = 38
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            Description = "Playera con guerrero águila ilustrado en el frente y glifos en la espalda. Algodón pesado de 200 g.",
                            ImageUrl = "/img/products/play-009.jpg",
                            Name = "Playera Guerrero Azteca",
                            Price = 319.00m,
                            Sku = "PLAY-009",
                            Stock = 47
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            Description = "Playera con patrón de azulejo de talavera repetido en todo el cuerpo. Estampado por sublimación.",
                            ImageUrl = "/img/products/play-010.jpg",
                            Name = "Playera Talavera Estampada",
                            Price = 289.00m,
                            Sku = "PLAY-010",
                            Stock = 66
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 4,
                            Description = "Pin de metal esmaltado en rosa con contorno dorado. Cierre de mariposa y respaldo grabado.",
                            ImageUrl = "/img/products/pins-001.jpg",
                            Name = "Pin Ajolote Rosa",
                            Price = 59.00m,
                            Sku = "PINS-001",
                            Stock = 130
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 4,
                            Description = "Calavera de azúcar en esmalte duro con flores de cempasúchil en naranja. Medida de 3 cm.",
                            ImageUrl = "/img/products/pins-002.jpg",
                            Name = "Pin Calavera Esmaltada",
                            Price = 65.00m,
                            Sku = "PINS-002",
                            Stock = 115
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 4,
                            Description = "Pin rectangular con la bandera nacional en esmalte suave y baño de níquel. El clásico de la vitrina.",
                            ImageUrl = "/img/products/pins-003.jpg",
                            Name = "Pin Bandera de México",
                            Price = 39.00m,
                            Sku = "PINS-003",
                            Stock = 140
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 4,
                            Description = "Pin de taco al pastor con piña, cilantro y tortilla en cinco colores de esmalte. Doble poste para que no gire.",
                            ImageUrl = "/img/products/pins-004.jpg",
                            Name = "Pin Taco al Pastor",
                            Price = 49.00m,
                            Sku = "PINS-004",
                            Stock = 126
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 4,
                            Description = "Nopal en metal con baño dorado y esmalte verde translúcido. Acabado espejo.",
                            ImageUrl = "/img/products/pins-005.jpg",
                            Name = "Pin Cactus Dorado",
                            Price = 55.00m,
                            Sku = "PINS-005",
                            Stock = 102
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 4,
                            Description = "Máscara de lucha libre en esmalte rojo, plata y negro. Coleccionable de la serie de tres modelos.",
                            ImageUrl = "/img/products/pins-006.jpg",
                            Name = "Pin Máscara de Luchador",
                            Price = 69.00m,
                            Sku = "PINS-006",
                            Stock = 87
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 4,
                            Description = "Colibrí en esmalte translúcido con degradado verde y azul sobre base de latón pulido.",
                            ImageUrl = "/img/products/pins-007.jpg",
                            Name = "Pin Colibrí Metálico",
                            Price = 79.00m,
                            Sku = "PINS-007",
                            Stock = 64
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 4,
                            Description = "Sombrero de mariachi en miniatura con grabado en el ala. El pin más económico del catálogo.",
                            ImageUrl = "/img/products/pins-008.jpg",
                            Name = "Pin Sombrero Mariachi",
                            Price = 35.00m,
                            Sku = "PINS-008",
                            Stock = 148
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 4,
                            Description = "Alebrije en esmalte de siete colores con detalles en línea negra. Réplica de una talla oaxaqueña.",
                            ImageUrl = "/img/products/pins-009.jpg",
                            Name = "Pin Alebrije Miniatura",
                            Price = 75.00m,
                            Sku = "PINS-009",
                            Stock = 79
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 4,
                            Description = "Pirámide de Chichén Itzá troquelada en metal con acabado bronce y fondo esmaltado en azul cielo.",
                            ImageUrl = "/img/products/pins-010.jpg",
                            Name = "Pin Pirámide Maya",
                            Price = 45.00m,
                            Sku = "PINS-010",
                            Stock = 133
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 5,
                            Description = "Libreta de tapa dura forrada en tela con bordado otomí. 160 hojas de papel crema rayado y cinta separadora.",
                            ImageUrl = "/img/products/libr-001.jpg",
                            Name = "Libreta Otomí Tapa Dura",
                            Price = 179.00m,
                            Sku = "LIBR-001",
                            Stock = 44
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 5,
                            Description = "Libreta tamaño A5 con portada de patrón de talavera y esquinas redondeadas. 120 hojas lisas.",
                            ImageUrl = "/img/products/libr-002.jpg",
                            Name = "Libreta Talavera A5",
                            Price = 149.00m,
                            Sku = "LIBR-002",
                            Stock = 68
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 5,
                            Description = "Libreta de encuadernación japonesa cosida a mano, con portada ilustrada de alebrije. 96 hojas.",
                            ImageUrl = "/img/products/libr-003.jpg",
                            Name = "Libreta Alebrije Cosida",
                            Price = 165.00m,
                            Sku = "LIBR-003",
                            Stock = 51
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 5,
                            Description = "Libreta de bolsillo de 9 x 14 cm con Catrina en la portada. 64 hojas rayadas, ideal para notas rápidas.",
                            ImageUrl = "/img/products/libr-004.jpg",
                            Name = "Libreta Catrina de Bolsillo",
                            Price = 89.00m,
                            Sku = "LIBR-004",
                            Stock = 112
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 5,
                            Description = "Libreta con portada de papel amate elaborado en San Pablito, Puebla. Cada portada tiene una textura distinta.",
                            ImageUrl = "/img/products/libr-005.jpg",
                            Name = "Libreta de Papel Amate",
                            Price = 159.00m,
                            Sku = "LIBR-005",
                            Stock = 33
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 5,
                            Description = "Libreta de espiral doble con las cartas de la lotería en la portada y separadores por sección. 140 hojas.",
                            ImageUrl = "/img/products/libr-006.jpg",
                            Name = "Libreta Lotería Espiral",
                            Price = 119.00m,
                            Sku = "LIBR-006",
                            Stock = 97
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 5,
                            Description = "Libreta plegada en acordeón que imita un códice, con reproducción de glifos en la portada. 40 caras.",
                            ImageUrl = "/img/products/libr-007.jpg",
                            Name = "Libreta Códice Prehispánico",
                            Price = 175.00m,
                            Sku = "LIBR-007",
                            Stock = 26
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 5,
                            Description = "Libreta de hoja punteada para bullet journal, con nopales ilustrados en la portada. 180 hojas de 100 g.",
                            ImageUrl = "/img/products/libr-008.jpg",
                            Name = "Libreta Cactus Punteada",
                            Price = 129.00m,
                            Sku = "LIBR-008",
                            Stock = 81
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 5,
                            Description = "Libreta con monarcas ilustradas en la portada y en los cantos de las hojas. 120 hojas rayadas.",
                            ImageUrl = "/img/products/libr-009.jpg",
                            Name = "Libreta Mariposa Monarca",
                            Price = 139.00m,
                            Sku = "LIBR-009",
                            Stock = 59
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 5,
                            Description = "Libreta forrada en piel repujada a mano con motivos prehispánicos y cierre de correa. 200 hojas de papel reciclado.",
                            ImageUrl = "/img/products/libr-010.jpg",
                            Name = "Libreta de Piel Repujada",
                            Price = 169.00m,
                            Sku = "LIBR-010",
                            Stock = 35
                        });
                });

            modelBuilder.Entity("Catalog.Infrastructure.Entities.Product", b =>
                {
                    b.HasOne("Catalog.Infrastructure.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
